file_format: "1"
id: numpad5x6
name: Numpad 5x6
type: shield
url: https://github.com/gtips/reviung/tree/master/reviung5
requires: [nice_nano_v2]  # SuperMini compatible

features:
  - keys
  - display
