manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2        # use "main" if you chose @main above
      import: app/west.yml
  self:
    path: config
